version: '3.4'

services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./symfony/:/var/www/symfony/
    networks:
      - playground

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - php-fpm
    volumes:
      - ./symfony/:/var/www/symfony/
    ports:
      - 8082:80
    networks:
      - playground

  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - 3306:3306
    # volumes:
    #   - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: playground
        MYSQL_USER: user
        MYSQL_PASSWORD: user
    networks:
      - playground

networks:
  playground:
